export const CONSTANTS = {
  STARTING_BALANCE: 20,
  KILL_REWARD: 5,
  FOUR_GENS_BONUS: 2,
  FIVE_GENS_BONUS: 4,
  GEN_BEFORE_HOOK_PENALTY: -3,
  LAST_GEN_PENALTY: -5,
  DOOR_OPENED_PENALTY: -5,
  HATCH_ESCAPE_PENALTY: -5,
  COOLDOWN_MATCHES: 2,
  DEATH_KILL_THRESHOLD: 3,
} as const;

export const STORAGE_KEYS = {
  RUN_DATA: 'runData',
  THEME_MODE: 'themeMode',
} as const;
